### ISSUE TITLE
Multiple Y Axises on left and right sides of chart

### ISSUE THREAD

**Issue by kxie4github** [timmolter/XChart#93] opened 2015-03-04 18:54 UTC
Y Axises on both side of the chart is a commonly needed feature

**Comment by hwaipy** [comment] 2015-03-05 03:08
Yeah.

Something like this, right?

![qq20150305-1](https://cloud.githubusercontent.com/assets/6906967/6498524/c41f495c-c327-11e4-921c-a1a980f6d029.png)

**Comment by kxie4github** [comment] 2015-03-05 08:03
Yes, exactly.

Thanks,
Kevin

**Comment by timmolter** [comment] 2015-03-05 08:41
This is a duplicate of : https://github.com/timmolter/XChart/issues/54

I'd pay someone to add the feature, if you know of anyone.

**Comment by timmolter** [comment] 2015-10-01 10:33
Bounty posted on issue #54 for this feature request

**Closed by timmolter** 2015-10-01 10:33 UTC
Labels: Feature Request
